import { Metadata } from "next";
import Link from "next/link";

import ParagraphHighlightText from "@/src/components/ParagraphHighlightText";
import ParagraphLink from "@/src/components/ParagraphLink";
import ParagraphText from "@/src/components/ParagraphText";
import CommonMetaData from "@/src/constants/metadata";

import ExtraPages from "./ExtraPages";
import Heading from "./Heading";
import SocialMedia from "./SocialMedia";

export const metadata: Metadata = {
    ...CommonMetaData,
    title: "About me",
    description: "Generated by create next app",
};

const About = () => {
    return (
        <div>
            <Heading />

            <ParagraphText>
                I am a Senior Full-Stack Developer with over four years of
                experience in the IT industry, specializing in cloud-based
                technologies and full-stack development. My expertise extends
                beyond technical skills to proficient client communication and
                effective team management. I excel in developing web
                applications using the{" "}
                <ParagraphHighlightText>MERN stack</ParagraphHighlightText>{" "}
                (MongoDB, Express.js, React JS, Node.js), coupled with a deep
                understanding of RDBMS like MySQL and NoSQL databases like
                MongoDB. My proficiency in front-end technologies, including
                <ParagraphHighlightText>React.js</ParagraphHighlightText> and
                <ParagraphHighlightText>TypeScript</ParagraphHighlightText>,
                enhances my ability to deliver comprehensive and user-friendly
                digital solutions. I am adept at initiating projects from
                scratch and steering them to completion with a focus on client
                satisfaction. My experience with{" "}
                <ParagraphHighlightText>AWS services</ParagraphHighlightText>{" "}
                like EC2, S3, DynamoDB, and various AWS deployment tools allows
                me to build scalable, secure cloud infrastructure, optimizing
                deployment processes and reducing system latency.
            </ParagraphText>

            <ParagraphText>
                In my role as a Full-Stack Developer, I specialize in maximizing
                the potential of AWS services. My expertise in cloud computing,
                combined with my full-stack development skills, enables me to
                offer end-to-end solutions that are innovative, reliable, and
                efficient. This skill set is crucial in today&apos;s technology
                landscape, where cloud infrastructure plays a pivotal role in
                the success of web applications.
            </ParagraphText>

            <ParagraphText>
                At <ParagraphLink href="https://7span.com">7Span</ParagraphLink>
                , my role as a Senior Full Stack Developer goes beyond just
                coding; it involves leading projects and managing teams with a
                strategic vision. I take pride in fostering a collaborative
                environment where team members can grow and excel. My approach
                to project management is centered on clear communication,
                setting realistic goals, and ensuring that every team member is
                aligned with the project&apos;s objectives. This leadership
                style has not only led to successful project completions but
                also to building strong, cohesive teams that are capable of
                tackling complex challenges in the tech industry.
            </ParagraphText>

            <ParagraphText>
                My journey in the tech world is deeply rooted in my educational
                background in Computer Engineering from{" "}
                <ParagraphHighlightText>
                    Gujarat Technological University
                </ParagraphHighlightText>
                . The rigorous curriculum provided me with a strong foundation
                in the principles of software development and cloud computing.
                Beyond my formal education, I am passionately committed to
                lifelong learning. I continuously seek out new knowledge and
                skills, whether through professional development courses, tech
                conferences, or self-study. This dedication to learning ensures
                that I remain at the cutting edge of technology, always ready to
                adapt and innovate in an ever-evolving industry.
            </ParagraphText>

            <ParagraphText>
                Outside of my professional endeavors, I engage in activities
                that fuel my creativity and broaden my perspective. Photography
                allows me to capture and appreciate the world&apos;s beauty and
                diversity, while travel opens my eyes to new cultures and
                experiences. Cooking is another passion that challenges me to
                experiment and innovate, much like in my professional work.
                These interests not only provide a creative outlet but also
                influence my approach to technology, encouraging me to think
                outside the box and bring a unique perspective to my work.
            </ParagraphText>

            <ParagraphText>
                As I look to the future, I am filled with excitement about the
                endless possibilities in the fields of software development and
                cloud computing. My career is a testament to the power of
                blending technical expertise with strong interpersonal skills,
                creativity, and a commitment to continuous learning. I am driven
                by the desire to explore new technologies, innovate solutions,
                and contribute meaningfully to the tech world, while also
                nurturing my personal growth and diverse interests.
            </ParagraphText>

            <ParagraphText>
                I&apos;m always eager to connect with like-minded individuals,
                discuss new technological trends, or simply share stories. Feel
                free to reach out for collaborations, discussions, or just a
                friendly conversation about the ever-evolving world of
                technology.
            </ParagraphText>

            <ParagraphText>
                You can reach me out on the following platforms:
            </ParagraphText>
            <SocialMedia />

            <ParagraphText>
                To connect further you can react out to me at{" "}
                <Link href="mailto:dev@harrsh.com">dev[at]harrsh.com</Link>.
            </ParagraphText>

            <ParagraphText>
                Here&apos;s a list of pages that curate my website
            </ParagraphText>
            <ExtraPages />
        </div>
    );
};

export default About;
