import React from "react";

import { Metadata } from "next";

import CommonMetaData from "../../constants/metadata";

export const metadata: Metadata = {
    ...CommonMetaData,
    title: "About me",
    description: "Generated by create next app",
};

const About = () => {
    return <div>About</div>;
};

export default About;
