import React from "react";

import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Hello hello!! | Harrsh Patel",
    description: "Generated by create next app",
};

const Home = () => {
    return <div>Home</div>;
};

export default Home;
