import React from "react";

import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Hello hello!! | Harrsh Patel",
    description: "Generated by create next app",
};

const Home = () => {
    return (
        <div>
            <div className="h-screen">One</div>
            <div className="h-screen">Two</div>
            <div className="h-screen">Three</div>
            <div className="h-screen">Four</div>
            <div className="h-screen">Five</div>
        </div>
    );
};

export default Home;
